stages:
  - test
  - publish
  - trigger_prep
  - trigger

include:
  - project: Northern.tech/Mender/mendertesting
    file:
      - qa-common/runner.yml
      - qa-common/retry.yml
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'
  - component: gitlab.com/Northern.tech/Mender/mendertesting/commit-lint@master
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'
  - component: gitlab.com/Northern.tech/Mender/mendertesting/publish-codecov@master
    inputs:
      coverage_file: coverage.lcov
      flag: unittests
      needs_job: tests+coverage

variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  tags:
    - oslo-xps
  retry: !reference [.qa-common-default-retry, retry]

tests+coverage:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/debian:12
  before_script:
    - !reference [.qa-common-network-apt-retry, before_script]
    - apt update && apt install -yyq g++ cmake make lcov
  script:
    - cmake -D COVERAGE=ON .
    - make --jobs=$(nproc --all) --keep-going coverage
    - make coverage
  artifacts:
    expire_in: 2w
    paths:
      - coverage.lcov

tests:32bit:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/debian:12
  before_script:
    - !reference [.qa-common-network-apt-retry, before_script]
    - apt update && apt install -yyq g++ g++-multilib cmake make lcov
  script:
    - cmake -D CMAKE_C_FLAGS="-m32" .
    - make --jobs=$(nproc --all) --keep-going
    - make check

tests:static-analysis:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/debian:12
  before_script:
    - !reference [.qa-common-network-apt-retry, before_script]
    - apt update && apt install -yyq g++ g++-multilib cmake make lcov
  script:
    - cmake -D CMAKE_C_FLAGS="-fanalyzer" .
    - make --jobs=$(nproc --all) --keep-going
